#!/bin/bash
## ===========================================设置各参数（不需要的可以删掉或者前面加# ）=============================================

# 设置ARGO参数 (不设置默认使用临时隧道，如果设置把前面的#去掉)
export TOK='eyJhIjoiNmYyZTc1MWE3MTI5ZWExZjI1ZTlhMjEzN2Q5ZDhjMDQiLCJ0IjoiODJjMDdmOTMtNDA2Zi00MDk3LTkwYzUtMzM5YzRjMzBhNjAyIiwicyI6Ik9ETmxOV1UyT0RjdE5UaGlZUzAwWWpBMExXRmxaVGd0WmpRelpXRm1NR1JtT0RjeiJ9'
export ARGO_DOMAIN='*'

#设置哪吒参数(NEZHA_TLS='1'开启tls,设置其他关闭tls)
export NEZHA_SERVER='*'
export NEZHA_KEY='*'
export NEZHA_PORT='*'
export NEZHA_TLS='0'

#设置app参数（默认x-ra-y参数，如果你更该了下载地址，需要修改UUID和VPATH）
export UUID='811e0051-95ea-47ca-a82e-ecb98f1e0763'
export VPATH='/vls'
export VMS_PATH='/vms'
export CF_IP='104.16.0.0'

## ===========================================设置x-ra-y下载地址（建议直接使用默认）===============================
# 设置amd64-X-A-R-Y下载地址（带内置配置版本）
export URL_BOT='https://github.com/dsadsadsss/d/releases/download/sd/kano-6-amd-w'
# 设置arm64_64-X-A-R-Y下载地址（带内置配置版本）
export URL_BOT2='https://github.com/dsadsadsss/d/releases/download/sd/kano-6-arm-w'

arch=$(uname -m)
echo $arch


# chmod 777 /tmp/app 
nohup sh starttmp
echo -----------
